package com.saic.usedcar.lottery.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_lottery_awards
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LotteryAwards {
    /**
     *
     * t_lottery_awards.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * 活动ID,t_lottery_scheme.id
     *
     * t_lottery_awards.scheme_id
     *
     * @mbg.generated
     */
    private Integer schemeId;

    /**
     * 奖品名称
     *
     * t_lottery_awards.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * 奖品URL
     *
     * t_lottery_awards.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * 活动日期
     *
     * t_lottery_awards.activity_date
     *
     * @mbg.generated
     */
    private Date activityDate;

    /**
     * 当时奖品上限
     *
     * t_lottery_awards.num_max
     *
     * @mbg.generated
     */
    private Integer numMax;

    /**
     * 已抽中奖品数量
     *
     * t_lottery_awards.num
     *
     * @mbg.generated
     */
    private Integer num;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSchemeId() {
        return schemeId;
    }

    public void setSchemeId(Integer schemeId) {
        this.schemeId = schemeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    public Date getActivityDate() {
        return activityDate;
    }

    public void setActivityDate(Date activityDate) {
        this.activityDate = activityDate;
    }

    public Integer getNumMax() {
        return numMax;
    }

    public void setNumMax(Integer numMax) {
        this.numMax = numMax;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }
}