package com.saic.usedcar.lottery.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_lottery_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LotteryLog {
    /**
     *
     * t_lottery_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * 活动ID,t_lottery_scheme.id
     *
     * t_lottery_log.scheme_id
     *
     * @mbg.generated
     */
    private Integer schemeId;

    /**
     * 用户ID, 未登录：0
     *
     * t_lottery_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * 用户名称
     *
     * t_lottery_log.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * 用户手机号码
     *
     * t_lottery_log.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     * 1.PC; 2.H5
     *
     * t_lottery_log.source
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     * 0.未登录; 1.已抽奖; 2.未中奖; 3.中奖
     *
     * t_lottery_log.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     * 中奖奖品ID, t_lottery_awards.id
     *
     * t_lottery_log.awards_id
     *
     * @mbg.generated
     */
    private Integer awardsId;

    /**
     * 点击时间
     *
     * t_lottery_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSchemeId() {
        return schemeId;
    }

    public void setSchemeId(Integer schemeId) {
        this.schemeId = schemeId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    public Byte getSource() {
        return source;
    }

    public void setSource(Byte source) {
        this.source = source;
    }

    public Integer getResult() {
        return result;
    }

    public void setResult(Integer result) {
        this.result = result;
    }

    public Integer getAwardsId() {
        return awardsId;
    }

    public void setAwardsId(Integer awardsId) {
        this.awardsId = awardsId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}