package com.saic.usedcar.lottery.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_lottery_scheme
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LotteryScheme {
    /**
     *
     * t_lottery_scheme.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * 活动名称
     *
     * t_lottery_scheme.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * 活动开始时间
     *
     * t_lottery_scheme.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     * 活动结束时间
     *
     * t_lottery_scheme.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * 中奖概率, 1000为百分百命中
     *
     * t_lottery_scheme.probability
     *
     * @mbg.generated
     */
    private Integer probability;

    /**
     * 中奖短信模板
     *
     * t_lottery_scheme.selected_sms_template
     *
     * @mbg.generated
     */
    private String selectedSmsTemplate;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Integer getProbability() {
        return probability;
    }

    public void setProbability(Integer probability) {
        this.probability = probability;
    }

    public String getSelectedSmsTemplate() {
        return selectedSmsTemplate;
    }

    public void setSelectedSmsTemplate(String selectedSmsTemplate) {
        this.selectedSmsTemplate = selectedSmsTemplate == null ? null : selectedSmsTemplate.trim();
    }
    
    /**
     * 
     * 功能描述: 判断活动是否在有效期内<br>
     *
     * @return
     */
    public boolean isEffective(){
        if(this.startTime == null || this.endTime == null){
            return false;
        }
        
        long now = System.currentTimeMillis();
        return this.startTime.getTime() <= now && this.endTime.getTime() > now;

    }
}